FROM node:21-alpine3.19

WORKDIR /app

COPY ./src/miniapp/yarn.lock ./src/miniapp/package.json ./

RUN yarn install --frozen-lockfile \
    && chmod -R a+rx /app/node_modules/.bin

COPY ./src/miniapp/ ./

CMD ["node", "./node_modules/vite/bin/vite.js", "--host", "0.0.0.0", "--port", "3000"]
