FROM node:21-alpine3.19

WORKDIR /app

COPY ./src/miniapp/yarn.lock ./src/miniapp/package.json ./

RUN yarn install --frozen-lockfile \
    && chmod -R a+rx /app/node_modules/.bin

COPY ./src/miniapp/ .

CMD ["yarn", "dev"]
