FROM node:21-alpine3.19 AS builder

WORKDIR /app

COPY ./src/miniapp/package.json ./src/miniapp/yarn.lock ./
RUN yarn install --frozen-lockfile

COPY ./src/miniapp/ ./
RUN yarn build

FROM nginx:1.27-alpine

COPY ./src/miniapp/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/docs/ /usr/share/nginx/html/

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
