FROM python:3.11-slim-bullseye AS build

WORKDIR app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . ./

WORKDIR ./src/internal/bg

ENV PYTHONPATH=".."

CMD ["celery", "-A", "tasks", "worker", "-B", "-l", "INFO"]
