FROM python:3.11-slim-bullseye AS build

WORKDIR app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . ./

WORKDIR ./src/internal/api

ENV PYTHONPATH=".."

CMD ["python", "run.py"]

